/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary": "#ffffff",
              "on-background": "#1a1c1c",
              "on-tertiary-container": "#5a5153",
              "on-tertiary-fixed": "#211a1c",
              "on-secondary": "#ffffff",
              "inverse-surface": "#2f3131",
              "on-secondary-fixed": "#3f0017",
              "on-secondary-fixed-variant": "#812240",
              "inverse-on-surface": "#f0f1f1",
              "on-tertiary-fixed-variant": "#4e4447",
              "secondary-fixed-dim": "#ffb1c1",
              "primary": "#884d5a",
              "primary-container": "#feb3c1",
              "primary-fixed": "#ffd9df",
              "on-secondary-container": "#781b39",
              "surface-dim": "#dadada",
              "on-error": "#ffffff",
              "on-error-container": "#93000a",
              "tertiary": "#665c5e",
              "on-primary-fixed-variant": "#6c3642",
              "outline-variant": "#d6c2c4",
              "outline": "#847375",
              "secondary-fixed": "#ffd9df",
              "on-surface": "#1a1c1c",
              "surface-container-low": "#f3f3f4",
              "tertiary-container": "#d2c4c7",
              "secondary-container": "#ff85a2",
              "tertiary-fixed-dim": "#d1c3c6",
              "surface-container-highest": "#e2e2e2",
              "surface-container-high": "#e8e8e8",
              "on-primary-fixed": "#370b18",
              "primary-fixed-dim": "#fdb2c0",
              "background": "#f9f9f9",
              "on-primary-container": "#7a424e",
              "error": "#ba1a1a",
              "surface-tint": "#884d5a",
              "surface": "#f9f9f9",
              "error-container": "#ffdad6",
              "surface-bright": "#f9f9f9",
              "on-tertiary": "#ffffff",
              "surface-variant": "#e2e2e2",
              "on-surface-variant": "#514345",
              "secondary": "#a03a57",
              "surface-container-lowest": "#ffffff",
              "surface-container": "#eeeeee",
              "tertiary-fixed": "#eddfe2",
              "inverse-primary": "#fdb2c0",
              "loopy-cream": "#FFF0F3",
              "loopy-pink": "#FEB3C1",
              "loopy-rose": "#FF85A2"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {
              "unit": "8px",
              "stack-gap": "24px",
              "gutter": "16px",
              "container-margin-dt": "40px",
              "container-margin-mb": "20px"
      },
      "fontFamily": {
              "label-sm": ["Plus Jakarta Sans", "sans-serif"],
              "headline-xl": ["Quicksand", "sans-serif"],
              "label-lg": ["Plus Jakarta Sans", "sans-serif"],
              "headline-lg": ["Quicksand", "sans-serif"],
              "body-lg": ["Quicksand", "sans-serif"],
              "body-md": ["Quicksand", "sans-serif"],
              "headline-md": ["Quicksand", "sans-serif"]
      },
      "fontSize": {
              "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "headline-xl": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-lg": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.04em", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "500"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "500"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
